//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pen_clothes.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetMaterial
    {
        public string Title { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public double MinCount { get; set; }
        public string Image { get; set; }
        public string MaterialType { get; set; }
        public string Supplier { get; set; }
    }
}
