//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pen_clothes.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string Title { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public string Поставщик { get; set; }
        public string Тип_материала { get; set; }
    }
}
